env:
  browser: true
  es6: true
  jquery: true
  node: true
extends: 'eslint:recommended'
exclude: '/dist/'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - 1
